// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import AceiteAutomaticoController from "./aceite_automatico_controller"
application.register("aceite-automatico", AceiteAutomaticoController)

import OrderActionsController from "./order_actions_controller"
application.register("order-actions", OrderActionsController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)
