#!/usr/bin/env ruby

puts "=== ROTAS DE AGENDAMENTO ==="
puts "GET    /admin/scheduling                    # Página principal de configurações"
puts "PATCH  /admin/scheduling/configuration     # Atualizar configurações"
puts "PATCH  /admin/scheduling/availability      # Atualizar disponibilidade"
puts "POST   /admin/scheduling/move_orders_to_production  # Mover para produção"
puts ""
puts "=== ROTAS DE PEDIDOS ==="
puts "GET    /admin/orders                       # Lista de pedidos"
puts "GET    /admin/orders/new                   # Criar novo pedido"
puts "GET    /admin/orders/:id                   # Ver pedido específico"
puts "GET    /admin/orders/:id/edit              # Editar pedido"
puts "PATCH  /admin/orders/:id                   # Atualizar pedido"
puts "DELETE /admin/orders/:id                   # Excluir pedido"
puts "POST   /admin/orders/:id/accept            # Aceitar pedido"
puts "PATCH  /admin/orders/:id/update_status     # Atualizar status"
puts "POST   /admin/orders/:id/cancel_scheduled_order  # Cancelar agendamento"
puts ""
puts "=== URLs PARA TESTAR ==="
puts "http://localhost:3000/admin/scheduling"
puts "http://localhost:3000/admin/orders"
puts "http://localhost:3000/admin/orders/new"
puts ""
puts "=== VERIFICAÇÕES ==="
puts "1. Certifique-se de que o servidor está rodando: rails server"
puts "2. Acesse: http://localhost:3000/admin/scheduling"
puts "3. Se der erro, verifique se todos os arquivos foram criados"
puts "4. Verifique se o banco de dados está configurado"